# Generated by Django 3.2.12 on 2022-03-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20220311_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='name',
        ),
    ]
